# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Test application

on:
  push:
    branches: [ qa, master ]
  pull_request:
    branches: [ qa, master ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: finish
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - run: unset _JAVA_OPTIONS
    - name: Build and Test
      run: chmod +x ../scripts/travisTest.sh && ../scripts/travisTest.sh
