# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Test application

on:
  push:
    branches: [ qa, master ]
  pull_request:
    branches: [ qa, master ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: finish
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - run: unset _JAVA_OPTIONS
    - name: Setting up OC
      run: |
          sudo mount --make-rshared /
          wget -nv https://github.com/openshift/origin/releases/download/v3.11.0/openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit.tar.gz
          tar -xvf openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit.tar.gz
          cd openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit
          export PATH=`pwd`:$PATH
          cd ..
          sudo mv ../scripts/daemon.json /etc/docker/
          sudo systemctl restart docker
          oc cluster up
    - name: Build and Test
      run: chmod +x ../scripts/travisTest.sh && ../scripts/travisTest.sh
